version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: mygarage-db-producao
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: turbo_thp
      POSTGRES_DB: mygarage
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
